/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: header.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "header.pb-c.h"
void   header__header__init
                     (Header__Header         *message)
{
  static Header__Header init_value = HEADER__HEADER__INIT;
  *message = init_value;
}
size_t header__header__get_packed_size
                     (const Header__Header *message)
{
  assert(message->base.descriptor == &header__header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t header__header__pack
                     (const Header__Header *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &header__header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t header__header__pack_to_buffer
                     (const Header__Header *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &header__header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Header__Header *
       header__header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Header__Header *)
     protobuf_c_message_unpack (&header__header__descriptor,
                                allocator, len, data);
}
void   header__header__free_unpacked
                     (Header__Header *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &header__header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const uint32_t header__header__seq__default_value = 0u;
static const ProtobufCFieldDescriptor header__header__field_descriptors[4] =
{
  {
    "sender",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Header__Header, sender),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Header__Header, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Header__Header, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Header__Header, seq),
    NULL,
    &header__header__seq__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned header__header__field_indices_by_name[] = {
  2,   /* field[2] = length */
  0,   /* field[0] = sender */
  3,   /* field[3] = seq */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange header__header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor header__header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Header.Header",
  "Header",
  "Header__Header",
  "Header",
  sizeof(Header__Header),
  4,
  header__header__field_descriptors,
  header__header__field_indices_by_name,
  1,  header__header__number_ranges,
  (ProtobufCMessageInit) header__header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue header__module__enum_values_by_number[14] =
{
  { "LCMD", "HEADER__MODULE__LCMD", 1 },
  { "VMDRIVER", "HEADER__MODULE__VMDRIVER", 2 },
  { "LCPD", "HEADER__MODULE__LCPD", 3 },
  { "LCMOND", "HEADER__MODULE__LCMOND", 4 },
  { "LCSNFD", "HEADER__MODULE__LCSNFD", 5 },
  { "VMCLOUDADAPTER", "HEADER__MODULE__VMCLOUDADAPTER", 6 },
  { "POSTMAN", "HEADER__MODULE__POSTMAN", 7 },
  { "LCRMD", "HEADER__MODULE__LCRMD", 8 },
  { "TALKER", "HEADER__MODULE__TALKER", 9 },
  { "THIRDADAPTER", "HEADER__MODULE__THIRDADAPTER", 10 },
  { "PMCLOUDADAPTER", "HEADER__MODULE__PMCLOUDADAPTER", 11 },
  { "MNTNCT", "HEADER__MODULE__MNTNCT", 12 },
  { "NOTIFICATIONCENTER", "HEADER__MODULE__NOTIFICATIONCENTER", 13 },
  { "STOREKEEPER", "HEADER__MODULE__STOREKEEPER", 14 },
};
static const ProtobufCIntRange header__module__value_ranges[] = {
{1, 0},{0, 14}
};
static const ProtobufCEnumValueIndex header__module__enum_values_by_name[14] =
{
  { "LCMD", 0 },
  { "LCMOND", 3 },
  { "LCPD", 2 },
  { "LCRMD", 7 },
  { "LCSNFD", 4 },
  { "MNTNCT", 11 },
  { "NOTIFICATIONCENTER", 12 },
  { "PMCLOUDADAPTER", 10 },
  { "POSTMAN", 6 },
  { "STOREKEEPER", 13 },
  { "TALKER", 8 },
  { "THIRDADAPTER", 9 },
  { "VMCLOUDADAPTER", 5 },
  { "VMDRIVER", 1 },
};
const ProtobufCEnumDescriptor header__module__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Header.Module",
  "Module",
  "Header__Module",
  "Header",
  14,
  header__module__enum_values_by_number,
  14,
  header__module__enum_values_by_name,
  1,
  header__module__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue header__type__enum_values_by_number[1] =
{
  { "UNICAST", "HEADER__TYPE__UNICAST", 1 },
};
static const ProtobufCIntRange header__type__value_ranges[] = {
{1, 0},{0, 1}
};
static const ProtobufCEnumValueIndex header__type__enum_values_by_name[1] =
{
  { "UNICAST", 0 },
};
const ProtobufCEnumDescriptor header__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Header.Type",
  "Type",
  "Header__Type",
  "Header",
  1,
  header__type__enum_values_by_number,
  1,
  header__type__enum_values_by_name,
  1,
  header__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
