/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: postman.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "postman.pb-c.h"
void   postman__policy__init
                     (Postman__Policy         *message)
{
  static Postman__Policy init_value = POSTMAN__POLICY__INIT;
  *message = init_value;
}
size_t postman__policy__get_packed_size
                     (const Postman__Policy *message)
{
  assert(message->base.descriptor == &postman__policy__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__policy__pack
                     (const Postman__Policy *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__policy__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__policy__pack_to_buffer
                     (const Postman__Policy *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__policy__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__Policy *
       postman__policy__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__Policy *)
     protobuf_c_message_unpack (&postman__policy__descriptor,
                                allocator, len, data);
}
void   postman__policy__free_unpacked
                     (Postman__Policy *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__policy__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__mail_identity__init
                     (Postman__MailIdentity         *message)
{
  static Postman__MailIdentity init_value = POSTMAN__MAIL_IDENTITY__INIT;
  *message = init_value;
}
size_t postman__mail_identity__get_packed_size
                     (const Postman__MailIdentity *message)
{
  assert(message->base.descriptor == &postman__mail_identity__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__mail_identity__pack
                     (const Postman__MailIdentity *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__mail_identity__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__mail_identity__pack_to_buffer
                     (const Postman__MailIdentity *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__mail_identity__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__MailIdentity *
       postman__mail_identity__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__MailIdentity *)
     protobuf_c_message_unpack (&postman__mail_identity__descriptor,
                                allocator, len, data);
}
void   postman__mail_identity__free_unpacked
                     (Postman__MailIdentity *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__mail_identity__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__alarm_event__init
                     (Postman__AlarmEvent         *message)
{
  static Postman__AlarmEvent init_value = POSTMAN__ALARM_EVENT__INIT;
  *message = init_value;
}
size_t postman__alarm_event__get_packed_size
                     (const Postman__AlarmEvent *message)
{
  assert(message->base.descriptor == &postman__alarm_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__alarm_event__pack
                     (const Postman__AlarmEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__alarm_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__alarm_event__pack_to_buffer
                     (const Postman__AlarmEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__alarm_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__AlarmEvent *
       postman__alarm_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__AlarmEvent *)
     protobuf_c_message_unpack (&postman__alarm_event__descriptor,
                                allocator, len, data);
}
void   postman__alarm_event__free_unpacked
                     (Postman__AlarmEvent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__alarm_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__license_expire_event__init
                     (Postman__LicenseExpireEvent         *message)
{
  static Postman__LicenseExpireEvent init_value = POSTMAN__LICENSE_EXPIRE_EVENT__INIT;
  *message = init_value;
}
size_t postman__license_expire_event__get_packed_size
                     (const Postman__LicenseExpireEvent *message)
{
  assert(message->base.descriptor == &postman__license_expire_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__license_expire_event__pack
                     (const Postman__LicenseExpireEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__license_expire_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__license_expire_event__pack_to_buffer
                     (const Postman__LicenseExpireEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__license_expire_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__LicenseExpireEvent *
       postman__license_expire_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__LicenseExpireEvent *)
     protobuf_c_message_unpack (&postman__license_expire_event__descriptor,
                                allocator, len, data);
}
void   postman__license_expire_event__free_unpacked
                     (Postman__LicenseExpireEvent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__license_expire_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__service_expire_event__init
                     (Postman__ServiceExpireEvent         *message)
{
  static Postman__ServiceExpireEvent init_value = POSTMAN__SERVICE_EXPIRE_EVENT__INIT;
  *message = init_value;
}
size_t postman__service_expire_event__get_packed_size
                     (const Postman__ServiceExpireEvent *message)
{
  assert(message->base.descriptor == &postman__service_expire_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__service_expire_event__pack
                     (const Postman__ServiceExpireEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__service_expire_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__service_expire_event__pack_to_buffer
                     (const Postman__ServiceExpireEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__service_expire_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__ServiceExpireEvent *
       postman__service_expire_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__ServiceExpireEvent *)
     protobuf_c_message_unpack (&postman__service_expire_event__descriptor,
                                allocator, len, data);
}
void   postman__service_expire_event__free_unpacked
                     (Postman__ServiceExpireEvent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__service_expire_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__resource_event__init
                     (Postman__ResourceEvent         *message)
{
  static Postman__ResourceEvent init_value = POSTMAN__RESOURCE_EVENT__INIT;
  *message = init_value;
}
size_t postman__resource_event__get_packed_size
                     (const Postman__ResourceEvent *message)
{
  assert(message->base.descriptor == &postman__resource_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__resource_event__pack
                     (const Postman__ResourceEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__resource_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__resource_event__pack_to_buffer
                     (const Postman__ResourceEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__resource_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__ResourceEvent *
       postman__resource_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__ResourceEvent *)
     protobuf_c_message_unpack (&postman__resource_event__descriptor,
                                allocator, len, data);
}
void   postman__resource_event__free_unpacked
                     (Postman__ResourceEvent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__resource_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__service_charge_event__init
                     (Postman__ServiceChargeEvent         *message)
{
  static Postman__ServiceChargeEvent init_value = POSTMAN__SERVICE_CHARGE_EVENT__INIT;
  *message = init_value;
}
size_t postman__service_charge_event__get_packed_size
                     (const Postman__ServiceChargeEvent *message)
{
  assert(message->base.descriptor == &postman__service_charge_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__service_charge_event__pack
                     (const Postman__ServiceChargeEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__service_charge_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__service_charge_event__pack_to_buffer
                     (const Postman__ServiceChargeEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__service_charge_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__ServiceChargeEvent *
       postman__service_charge_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__ServiceChargeEvent *)
     protobuf_c_message_unpack (&postman__service_charge_event__descriptor,
                                allocator, len, data);
}
void   postman__service_charge_event__free_unpacked
                     (Postman__ServiceChargeEvent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__service_charge_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__instance_charge_event__init
                     (Postman__InstanceChargeEvent         *message)
{
  static Postman__InstanceChargeEvent init_value = POSTMAN__INSTANCE_CHARGE_EVENT__INIT;
  *message = init_value;
}
size_t postman__instance_charge_event__get_packed_size
                     (const Postman__InstanceChargeEvent *message)
{
  assert(message->base.descriptor == &postman__instance_charge_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__instance_charge_event__pack
                     (const Postman__InstanceChargeEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__instance_charge_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__instance_charge_event__pack_to_buffer
                     (const Postman__InstanceChargeEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__instance_charge_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__InstanceChargeEvent *
       postman__instance_charge_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__InstanceChargeEvent *)
     protobuf_c_message_unpack (&postman__instance_charge_event__descriptor,
                                allocator, len, data);
}
void   postman__instance_charge_event__free_unpacked
                     (Postman__InstanceChargeEvent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__instance_charge_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__user_balance_event__init
                     (Postman__UserBalanceEvent         *message)
{
  static Postman__UserBalanceEvent init_value = POSTMAN__USER_BALANCE_EVENT__INIT;
  *message = init_value;
}
size_t postman__user_balance_event__get_packed_size
                     (const Postman__UserBalanceEvent *message)
{
  assert(message->base.descriptor == &postman__user_balance_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__user_balance_event__pack
                     (const Postman__UserBalanceEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__user_balance_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__user_balance_event__pack_to_buffer
                     (const Postman__UserBalanceEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__user_balance_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__UserBalanceEvent *
       postman__user_balance_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__UserBalanceEvent *)
     protobuf_c_message_unpack (&postman__user_balance_event__descriptor,
                                allocator, len, data);
}
void   postman__user_balance_event__free_unpacked
                     (Postman__UserBalanceEvent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__user_balance_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__net_resource_usage__init
                     (Postman__NetResourceUsage         *message)
{
  static Postman__NetResourceUsage init_value = POSTMAN__NET_RESOURCE_USAGE__INIT;
  *message = init_value;
}
size_t postman__net_resource_usage__get_packed_size
                     (const Postman__NetResourceUsage *message)
{
  assert(message->base.descriptor == &postman__net_resource_usage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__net_resource_usage__pack
                     (const Postman__NetResourceUsage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__net_resource_usage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__net_resource_usage__pack_to_buffer
                     (const Postman__NetResourceUsage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__net_resource_usage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__NetResourceUsage *
       postman__net_resource_usage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__NetResourceUsage *)
     protobuf_c_message_unpack (&postman__net_resource_usage__descriptor,
                                allocator, len, data);
}
void   postman__net_resource_usage__free_unpacked
                     (Postman__NetResourceUsage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__net_resource_usage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__user_usage_form_event__init
                     (Postman__UserUsageFormEvent         *message)
{
  static Postman__UserUsageFormEvent init_value = POSTMAN__USER_USAGE_FORM_EVENT__INIT;
  *message = init_value;
}
size_t postman__user_usage_form_event__get_packed_size
                     (const Postman__UserUsageFormEvent *message)
{
  assert(message->base.descriptor == &postman__user_usage_form_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__user_usage_form_event__pack
                     (const Postman__UserUsageFormEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__user_usage_form_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__user_usage_form_event__pack_to_buffer
                     (const Postman__UserUsageFormEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__user_usage_form_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__UserUsageFormEvent *
       postman__user_usage_form_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__UserUsageFormEvent *)
     protobuf_c_message_unpack (&postman__user_usage_form_event__descriptor,
                                allocator, len, data);
}
void   postman__user_usage_form_event__free_unpacked
                     (Postman__UserUsageFormEvent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__user_usage_form_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__user_charge_form_event__init
                     (Postman__UserChargeFormEvent         *message)
{
  static Postman__UserChargeFormEvent init_value = POSTMAN__USER_CHARGE_FORM_EVENT__INIT;
  *message = init_value;
}
size_t postman__user_charge_form_event__get_packed_size
                     (const Postman__UserChargeFormEvent *message)
{
  assert(message->base.descriptor == &postman__user_charge_form_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__user_charge_form_event__pack
                     (const Postman__UserChargeFormEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__user_charge_form_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__user_charge_form_event__pack_to_buffer
                     (const Postman__UserChargeFormEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__user_charge_form_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__UserChargeFormEvent *
       postman__user_charge_form_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__UserChargeFormEvent *)
     protobuf_c_message_unpack (&postman__user_charge_form_event__descriptor,
                                allocator, len, data);
}
void   postman__user_charge_form_event__free_unpacked
                     (Postman__UserChargeFormEvent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__user_charge_form_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__mail_content__init
                     (Postman__MailContent         *message)
{
  static Postman__MailContent init_value = POSTMAN__MAIL_CONTENT__INIT;
  *message = init_value;
}
size_t postman__mail_content__get_packed_size
                     (const Postman__MailContent *message)
{
  assert(message->base.descriptor == &postman__mail_content__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__mail_content__pack
                     (const Postman__MailContent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__mail_content__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__mail_content__pack_to_buffer
                     (const Postman__MailContent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__mail_content__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__MailContent *
       postman__mail_content__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__MailContent *)
     protobuf_c_message_unpack (&postman__mail_content__descriptor,
                                allocator, len, data);
}
void   postman__mail_content__free_unpacked
                     (Postman__MailContent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__mail_content__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__mail__init
                     (Postman__Mail         *message)
{
  static Postman__Mail init_value = POSTMAN__MAIL__INIT;
  *message = init_value;
}
size_t postman__mail__get_packed_size
                     (const Postman__Mail *message)
{
  assert(message->base.descriptor == &postman__mail__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__mail__pack
                     (const Postman__Mail *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__mail__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__mail__pack_to_buffer
                     (const Postman__Mail *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__mail__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__Mail *
       postman__mail__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__Mail *)
     protobuf_c_message_unpack (&postman__mail__descriptor,
                                allocator, len, data);
}
void   postman__mail__free_unpacked
                     (Postman__Mail *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__mail__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__send_request__init
                     (Postman__SendRequest         *message)
{
  static Postman__SendRequest init_value = POSTMAN__SEND_REQUEST__INIT;
  *message = init_value;
}
size_t postman__send_request__get_packed_size
                     (const Postman__SendRequest *message)
{
  assert(message->base.descriptor == &postman__send_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__send_request__pack
                     (const Postman__SendRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__send_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__send_request__pack_to_buffer
                     (const Postman__SendRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__send_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__SendRequest *
       postman__send_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__SendRequest *)
     protobuf_c_message_unpack (&postman__send_request__descriptor,
                                allocator, len, data);
}
void   postman__send_request__free_unpacked
                     (Postman__SendRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__send_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   postman__message__init
                     (Postman__Message         *message)
{
  static Postman__Message init_value = POSTMAN__MESSAGE__INIT;
  *message = init_value;
}
size_t postman__message__get_packed_size
                     (const Postman__Message *message)
{
  assert(message->base.descriptor == &postman__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t postman__message__pack
                     (const Postman__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &postman__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t postman__message__pack_to_buffer
                     (const Postman__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &postman__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Postman__Message *
       postman__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Postman__Message *)
     protobuf_c_message_unpack (&postman__message__descriptor,
                                allocator, len, data);
}
void   postman__message__free_unpacked
                     (Postman__Message *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &postman__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const Postman__Priority postman__policy__priority__default_value = POSTMAN__PRIORITY__NORMAL;
static const Postman__AggregateId postman__policy__aggregate_id__default_value = POSTMAN__AGGREGATE_ID__AGG_NO_AGGREGATE;
static const uint32_t postman__policy__aggregate_window__default_value = 0u;
static const uint32_t postman__policy__min_event_interval__default_value = 0u;
static const uint32_t postman__policy__min_dest_interval__default_value = 0u;
static const ProtobufCFieldDescriptor postman__policy__field_descriptors[6] =
{
  {
    "priority",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Postman__Policy, has_priority),
    offsetof(Postman__Policy, priority),
    &postman__priority__descriptor,
    &postman__policy__priority__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aggregate_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Postman__Policy, has_aggregate_id),
    offsetof(Postman__Policy, aggregate_id),
    &postman__aggregate_id__descriptor,
    &postman__policy__aggregate_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aggregate_window",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__Policy, has_aggregate_window),
    offsetof(Postman__Policy, aggregate_window),
    NULL,
    &postman__policy__aggregate_window__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min_event_interval",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__Policy, has_min_event_interval),
    offsetof(Postman__Policy, min_event_interval),
    NULL,
    &postman__policy__min_event_interval__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min_dest_interval",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__Policy, has_min_dest_interval),
    offsetof(Postman__Policy, min_dest_interval),
    NULL,
    &postman__policy__min_dest_interval__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "issue_timestamp",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__Policy, has_issue_timestamp),
    offsetof(Postman__Policy, issue_timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__policy__field_indices_by_name[] = {
  1,   /* field[1] = aggregate_id */
  2,   /* field[2] = aggregate_window */
  5,   /* field[5] = issue_timestamp */
  4,   /* field[4] = min_dest_interval */
  3,   /* field[3] = min_event_interval */
  0,   /* field[0] = priority */
};
static const ProtobufCIntRange postman__policy__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor postman__policy__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.Policy",
  "Policy",
  "Postman__Policy",
  "Postman",
  sizeof(Postman__Policy),
  6,
  postman__policy__field_descriptors,
  postman__policy__field_indices_by_name,
  1,  postman__policy__number_ranges,
  (ProtobufCMessageInit) postman__policy__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__mail_identity__field_descriptors[3] =
{
  {
    "event_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Postman__MailIdentity, has_event_type),
    offsetof(Postman__MailIdentity, event_type),
    &postman__event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resource_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Postman__MailIdentity, has_resource_type),
    offsetof(Postman__MailIdentity, resource_type),
    &postman__resource__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resource_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__MailIdentity, has_resource_id),
    offsetof(Postman__MailIdentity, resource_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__mail_identity__field_indices_by_name[] = {
  0,   /* field[0] = event_type */
  2,   /* field[2] = resource_id */
  1,   /* field[1] = resource_type */
};
static const ProtobufCIntRange postman__mail_identity__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor postman__mail_identity__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.MailIdentity",
  "MailIdentity",
  "Postman__MailIdentity",
  "Postman",
  sizeof(Postman__MailIdentity),
  3,
  postman__mail_identity__field_descriptors,
  postman__mail_identity__field_indices_by_name,
  1,  postman__mail_identity__number_ranges,
  (ProtobufCMessageInit) postman__mail_identity__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__alarm_event__field_descriptors[5] =
{
  {
    "resource_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__AlarmEvent, resource_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resource_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__AlarmEvent, resource_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alarm_begin",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__AlarmEvent, has_alarm_begin),
    offsetof(Postman__AlarmEvent, alarm_begin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alarm_last",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__AlarmEvent, has_alarm_last),
    offsetof(Postman__AlarmEvent, alarm_last),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alarm_message",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__AlarmEvent, alarm_message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__alarm_event__field_indices_by_name[] = {
  2,   /* field[2] = alarm_begin */
  3,   /* field[3] = alarm_last */
  4,   /* field[4] = alarm_message */
  1,   /* field[1] = resource_name */
  0,   /* field[0] = resource_type */
};
static const ProtobufCIntRange postman__alarm_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor postman__alarm_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.AlarmEvent",
  "AlarmEvent",
  "Postman__AlarmEvent",
  "Postman",
  sizeof(Postman__AlarmEvent),
  5,
  postman__alarm_event__field_descriptors,
  postman__alarm_event__field_indices_by_name,
  1,  postman__alarm_event__number_ranges,
  (ProtobufCMessageInit) postman__alarm_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__license_expire_event__field_descriptors[11] =
{
  {
    "host_ip",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__LicenseExpireEvent, host_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_count",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__LicenseExpireEvent, has_host_count),
    offsetof(Postman__LicenseExpireEvent, host_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_vm_count",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__LicenseExpireEvent, has_host_vm_count),
    offsetof(Postman__LicenseExpireEvent, host_vm_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rack_name",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__LicenseExpireEvent, rack_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rack_location",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__LicenseExpireEvent, rack_location),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rack_usage_days",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__LicenseExpireEvent, has_rack_usage_days),
    offsetof(Postman__LicenseExpireEvent, rack_usage_days),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "activate_time",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__LicenseExpireEvent, has_activate_time),
    offsetof(Postman__LicenseExpireEvent, activate_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expire_time",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__LicenseExpireEvent, has_expire_time),
    offsetof(Postman__LicenseExpireEvent, expire_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_limit",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__LicenseExpireEvent, has_host_limit),
    offsetof(Postman__LicenseExpireEvent, host_limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "domain_id",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__LicenseExpireEvent, has_domain_id),
    offsetof(Postman__LicenseExpireEvent, domain_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "domain",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__LicenseExpireEvent, domain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__license_expire_event__field_indices_by_name[] = {
  6,   /* field[6] = activate_time */
  10,   /* field[10] = domain */
  9,   /* field[9] = domain_id */
  7,   /* field[7] = expire_time */
  1,   /* field[1] = host_count */
  0,   /* field[0] = host_ip */
  8,   /* field[8] = host_limit */
  2,   /* field[2] = host_vm_count */
  4,   /* field[4] = rack_location */
  3,   /* field[3] = rack_name */
  5,   /* field[5] = rack_usage_days */
};
static const ProtobufCIntRange postman__license_expire_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor postman__license_expire_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.LicenseExpireEvent",
  "LicenseExpireEvent",
  "Postman__LicenseExpireEvent",
  "Postman",
  sizeof(Postman__LicenseExpireEvent),
  11,
  postman__license_expire_event__field_descriptors,
  postman__license_expire_event__field_indices_by_name,
  1,  postman__license_expire_event__number_ranges,
  (ProtobufCMessageInit) postman__license_expire_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__service_expire_event__field_descriptors[12] =
{
  {
    "resource_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceExpireEvent, resource_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resource_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceExpireEvent, resource_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resource_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceExpireEvent, resource_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_time",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__ServiceExpireEvent, has_create_time),
    offsetof(Postman__ServiceExpireEvent, create_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resource_state",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceExpireEvent, resource_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vcpu_num",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__ServiceExpireEvent, has_vcpu_num),
    offsetof(Postman__ServiceExpireEvent, vcpu_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_size",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__ServiceExpireEvent, has_mem_size),
    offsetof(Postman__ServiceExpireEvent, mem_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vdi_sys_size",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__ServiceExpireEvent, has_vdi_sys_size),
    offsetof(Postman__ServiceExpireEvent, vdi_sys_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vdi_user_size",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__ServiceExpireEvent, has_vdi_user_size),
    offsetof(Postman__ServiceExpireEvent, vdi_user_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remark",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceExpireEvent, remark),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "domain_id",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__ServiceExpireEvent, has_domain_id),
    offsetof(Postman__ServiceExpireEvent, domain_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "domain",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceExpireEvent, domain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__service_expire_event__field_indices_by_name[] = {
  3,   /* field[3] = create_time */
  11,   /* field[11] = domain */
  10,   /* field[10] = domain_id */
  6,   /* field[6] = mem_size */
  9,   /* field[9] = remark */
  2,   /* field[2] = resource_id */
  1,   /* field[1] = resource_name */
  4,   /* field[4] = resource_state */
  0,   /* field[0] = resource_type */
  5,   /* field[5] = vcpu_num */
  7,   /* field[7] = vdi_sys_size */
  8,   /* field[8] = vdi_user_size */
};
static const ProtobufCIntRange postman__service_expire_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor postman__service_expire_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.ServiceExpireEvent",
  "ServiceExpireEvent",
  "Postman__ServiceExpireEvent",
  "Postman",
  sizeof(Postman__ServiceExpireEvent),
  12,
  postman__service_expire_event__field_descriptors,
  postman__service_expire_event__field_indices_by_name,
  1,  postman__service_expire_event__number_ranges,
  (ProtobufCMessageInit) postman__service_expire_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__resource_event__field_descriptors[5] =
{
  {
    "resource_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ResourceEvent, resource_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resource_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ResourceEvent, resource_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operate_time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__ResourceEvent, has_operate_time),
    offsetof(Postman__ResourceEvent, operate_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operate_type",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ResourceEvent, operate_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remark",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ResourceEvent, remark),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__resource_event__field_indices_by_name[] = {
  2,   /* field[2] = operate_time */
  3,   /* field[3] = operate_type */
  4,   /* field[4] = remark */
  1,   /* field[1] = resource_name */
  0,   /* field[0] = resource_type */
};
static const ProtobufCIntRange postman__resource_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor postman__resource_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.ResourceEvent",
  "ResourceEvent",
  "Postman__ResourceEvent",
  "Postman",
  sizeof(Postman__ResourceEvent),
  5,
  postman__resource_event__field_descriptors,
  postman__resource_event__field_indices_by_name,
  1,  postman__resource_event__number_ranges,
  (ProtobufCMessageInit) postman__resource_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__service_charge_event__field_descriptors[11] =
{
  {
    "service_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceChargeEvent, service_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instance_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceChargeEvent, instance_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__ServiceChargeEvent, has_start_time),
    offsetof(Postman__ServiceChargeEvent, start_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_time",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__ServiceChargeEvent, has_end_time),
    offsetof(Postman__ServiceChargeEvent, end_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__ServiceChargeEvent, has_size),
    offsetof(Postman__ServiceChargeEvent, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cumulative_time",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceChargeEvent, cumulative_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "price",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceChargeEvent, price),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "settlement_amount",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceChargeEvent, settlement_amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remark",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceChargeEvent, remark),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "domain_id",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__ServiceChargeEvent, has_domain_id),
    offsetof(Postman__ServiceChargeEvent, domain_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "domain",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__ServiceChargeEvent, domain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__service_charge_event__field_indices_by_name[] = {
  5,   /* field[5] = cumulative_time */
  10,   /* field[10] = domain */
  9,   /* field[9] = domain_id */
  3,   /* field[3] = end_time */
  1,   /* field[1] = instance_name */
  6,   /* field[6] = price */
  8,   /* field[8] = remark */
  0,   /* field[0] = service_name */
  7,   /* field[7] = settlement_amount */
  4,   /* field[4] = size */
  2,   /* field[2] = start_time */
};
static const ProtobufCIntRange postman__service_charge_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor postman__service_charge_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.ServiceChargeEvent",
  "ServiceChargeEvent",
  "Postman__ServiceChargeEvent",
  "Postman",
  sizeof(Postman__ServiceChargeEvent),
  11,
  postman__service_charge_event__field_descriptors,
  postman__service_charge_event__field_indices_by_name,
  1,  postman__service_charge_event__number_ranges,
  (ProtobufCMessageInit) postman__service_charge_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__instance_charge_event__field_descriptors[10] =
{
  {
    "instance_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__InstanceChargeEvent, instance_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__InstanceChargeEvent, has_start_time),
    offsetof(Postman__InstanceChargeEvent, start_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__InstanceChargeEvent, has_end_time),
    offsetof(Postman__InstanceChargeEvent, end_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cumulative_time",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__InstanceChargeEvent, cumulative_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "price",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__InstanceChargeEvent, price),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "settlement_amount",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__InstanceChargeEvent, settlement_amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remark",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__InstanceChargeEvent, remark),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__InstanceChargeEvent, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "domain_id",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__InstanceChargeEvent, has_domain_id),
    offsetof(Postman__InstanceChargeEvent, domain_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "domain",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__InstanceChargeEvent, domain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__instance_charge_event__field_indices_by_name[] = {
  3,   /* field[3] = cumulative_time */
  9,   /* field[9] = domain */
  8,   /* field[8] = domain_id */
  2,   /* field[2] = end_time */
  0,   /* field[0] = instance_name */
  4,   /* field[4] = price */
  6,   /* field[6] = remark */
  5,   /* field[5] = settlement_amount */
  1,   /* field[1] = start_time */
  7,   /* field[7] = type */
};
static const ProtobufCIntRange postman__instance_charge_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor postman__instance_charge_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.InstanceChargeEvent",
  "InstanceChargeEvent",
  "Postman__InstanceChargeEvent",
  "Postman",
  sizeof(Postman__InstanceChargeEvent),
  10,
  postman__instance_charge_event__field_descriptors,
  postman__instance_charge_event__field_indices_by_name,
  1,  postman__instance_charge_event__number_ranges,
  (ProtobufCMessageInit) postman__instance_charge_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__user_balance_event__field_descriptors[6] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserBalanceEvent, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "email",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserBalanceEvent, email),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "balance",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserBalanceEvent, balance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "company",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserBalanceEvent, company),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone_num",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserBalanceEvent, phone_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_type",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserBalanceEvent, user_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__user_balance_event__field_indices_by_name[] = {
  2,   /* field[2] = balance */
  3,   /* field[3] = company */
  1,   /* field[1] = email */
  4,   /* field[4] = phone_num */
  5,   /* field[5] = user_type */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange postman__user_balance_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor postman__user_balance_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.UserBalanceEvent",
  "UserBalanceEvent",
  "Postman__UserBalanceEvent",
  "Postman",
  sizeof(Postman__UserBalanceEvent),
  6,
  postman__user_balance_event__field_descriptors,
  postman__user_balance_event__field_indices_by_name,
  1,  postman__user_balance_event__number_ranges,
  (ProtobufCMessageInit) postman__user_balance_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__net_resource_usage__field_descriptors[5] =
{
  {
    "domain_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__NetResourceUsage, has_domain_id),
    offsetof(Postman__NetResourceUsage, domain_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "domain",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__NetResourceUsage, domain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isp_name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__NetResourceUsage, isp_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bandwidth",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__NetResourceUsage, bandwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isp_count",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__NetResourceUsage, has_isp_count),
    offsetof(Postman__NetResourceUsage, isp_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__net_resource_usage__field_indices_by_name[] = {
  3,   /* field[3] = bandwidth */
  1,   /* field[1] = domain */
  0,   /* field[0] = domain_id */
  4,   /* field[4] = isp_count */
  2,   /* field[2] = isp_name */
};
static const ProtobufCIntRange postman__net_resource_usage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor postman__net_resource_usage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.NetResourceUsage",
  "NetResourceUsage",
  "Postman__NetResourceUsage",
  "Postman",
  sizeof(Postman__NetResourceUsage),
  5,
  postman__net_resource_usage__field_descriptors,
  postman__net_resource_usage__field_indices_by_name,
  1,  postman__net_resource_usage__number_ranges,
  (ProtobufCMessageInit) postman__net_resource_usage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__user_usage_form_event__field_descriptors[12] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserUsageFormEvent, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "company",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserUsageFormEvent, company),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "industry",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserUsageFormEvent, industry),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contact",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserUsageFormEvent, contact),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserUsageFormEvent, phone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_time",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__UserUsageFormEvent, has_create_time),
    offsetof(Postman__UserUsageFormEvent, create_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isp_name",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserUsageFormEvent, isp_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bandwidth",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserUsageFormEvent, bandwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isp_count",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__UserUsageFormEvent, has_isp_count),
    offsetof(Postman__UserUsageFormEvent, isp_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vms",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Postman__UserUsageFormEvent, n_vms),
    offsetof(Postman__UserUsageFormEvent, vms),
    &postman__service_expire_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "events",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Postman__UserUsageFormEvent, n_events),
    offsetof(Postman__UserUsageFormEvent, events),
    &postman__resource_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nets",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Postman__UserUsageFormEvent, n_nets),
    offsetof(Postman__UserUsageFormEvent, nets),
    &postman__net_resource_usage__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__user_usage_form_event__field_indices_by_name[] = {
  7,   /* field[7] = bandwidth */
  1,   /* field[1] = company */
  3,   /* field[3] = contact */
  5,   /* field[5] = create_time */
  10,   /* field[10] = events */
  2,   /* field[2] = industry */
  8,   /* field[8] = isp_count */
  6,   /* field[6] = isp_name */
  11,   /* field[11] = nets */
  4,   /* field[4] = phone */
  0,   /* field[0] = username */
  9,   /* field[9] = vms */
};
static const ProtobufCIntRange postman__user_usage_form_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor postman__user_usage_form_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.UserUsageFormEvent",
  "UserUsageFormEvent",
  "Postman__UserUsageFormEvent",
  "Postman",
  sizeof(Postman__UserUsageFormEvent),
  12,
  postman__user_usage_form_event__field_descriptors,
  postman__user_usage_form_event__field_indices_by_name,
  1,  postman__user_usage_form_event__number_ranges,
  (ProtobufCMessageInit) postman__user_usage_form_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__user_charge_form_event__field_descriptors[12] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserChargeFormEvent, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "company",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserChargeFormEvent, company),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "industry",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserChargeFormEvent, industry),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contact",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserChargeFormEvent, contact),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserChargeFormEvent, phone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_time",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Postman__UserChargeFormEvent, has_create_time),
    offsetof(Postman__UserChargeFormEvent, create_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "balance",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserChargeFormEvent, balance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "daily_account",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserChargeFormEvent, daily_account),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "available_time",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__UserChargeFormEvent, available_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "services",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Postman__UserChargeFormEvent, n_services),
    offsetof(Postman__UserChargeFormEvent, services),
    &postman__service_charge_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instances",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Postman__UserChargeFormEvent, n_instances),
    offsetof(Postman__UserChargeFormEvent, instances),
    &postman__instance_charge_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_balances",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Postman__UserChargeFormEvent, n_user_balances),
    offsetof(Postman__UserChargeFormEvent, user_balances),
    &postman__user_balance_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__user_charge_form_event__field_indices_by_name[] = {
  8,   /* field[8] = available_time */
  6,   /* field[6] = balance */
  1,   /* field[1] = company */
  3,   /* field[3] = contact */
  5,   /* field[5] = create_time */
  7,   /* field[7] = daily_account */
  2,   /* field[2] = industry */
  10,   /* field[10] = instances */
  4,   /* field[4] = phone */
  9,   /* field[9] = services */
  11,   /* field[11] = user_balances */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange postman__user_charge_form_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor postman__user_charge_form_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.UserChargeFormEvent",
  "UserChargeFormEvent",
  "Postman__UserChargeFormEvent",
  "Postman",
  sizeof(Postman__UserChargeFormEvent),
  12,
  postman__user_charge_form_event__field_descriptors,
  postman__user_charge_form_event__field_indices_by_name,
  1,  postman__user_charge_form_event__number_ranges,
  (ProtobufCMessageInit) postman__user_charge_form_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__mail_content__field_descriptors[10] =
{
  {
    "head_template",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__MailContent, head_template),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tail_template",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__MailContent, tail_template),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attachments",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Postman__MailContent, n_attachments),
    offsetof(Postman__MailContent, attachments),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mail_type",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Postman__MailContent, has_mail_type),
    offsetof(Postman__MailContent, mail_type),
    &postman__mail_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alarms",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Postman__MailContent, n_alarms),
    offsetof(Postman__MailContent, alarms),
    &postman__alarm_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "license_expires",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Postman__MailContent, n_license_expires),
    offsetof(Postman__MailContent, license_expires),
    &postman__license_expire_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service_expires",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Postman__MailContent, n_service_expires),
    offsetof(Postman__MailContent, service_expires),
    &postman__service_expire_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_usage_form",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Postman__MailContent, user_usage_form),
    &postman__user_usage_form_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_charge_form",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Postman__MailContent, user_charge_form),
    &postman__user_charge_form_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "raw_string",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__MailContent, raw_string),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__mail_content__field_indices_by_name[] = {
  4,   /* field[4] = alarms */
  2,   /* field[2] = attachments */
  0,   /* field[0] = head_template */
  5,   /* field[5] = license_expires */
  3,   /* field[3] = mail_type */
  9,   /* field[9] = raw_string */
  6,   /* field[6] = service_expires */
  1,   /* field[1] = tail_template */
  8,   /* field[8] = user_charge_form */
  7,   /* field[7] = user_usage_form */
};
static const ProtobufCIntRange postman__mail_content__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor postman__mail_content__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.MailContent",
  "MailContent",
  "Postman__MailContent",
  "Postman",
  sizeof(Postman__MailContent),
  10,
  postman__mail_content__field_descriptors,
  postman__mail_content__field_indices_by_name,
  1,  postman__mail_content__number_ranges,
  (ProtobufCMessageInit) postman__mail_content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__mail__field_descriptors[7] =
{
  {
    "from",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__Mail, from),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__Mail, to),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cc",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__Mail, cc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bcc",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__Mail, bcc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__Mail, subject),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "customer_name",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Postman__Mail, customer_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Postman__Mail, content),
    &postman__mail_content__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__mail__field_indices_by_name[] = {
  3,   /* field[3] = bcc */
  2,   /* field[2] = cc */
  6,   /* field[6] = content */
  5,   /* field[5] = customer_name */
  0,   /* field[0] = from */
  4,   /* field[4] = subject */
  1,   /* field[1] = to */
};
static const ProtobufCIntRange postman__mail__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor postman__mail__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.Mail",
  "Mail",
  "Postman__Mail",
  "Postman",
  sizeof(Postman__Mail),
  7,
  postman__mail__field_descriptors,
  postman__mail__field_indices_by_name,
  1,  postman__mail__number_ranges,
  (ProtobufCMessageInit) postman__mail__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__send_request__field_descriptors[3] =
{
  {
    "policy",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Postman__SendRequest, policy),
    &postman__policy__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Postman__SendRequest, id),
    &postman__mail_identity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mail",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Postman__SendRequest, mail),
    &postman__mail__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__send_request__field_indices_by_name[] = {
  1,   /* field[1] = id */
  2,   /* field[2] = mail */
  0,   /* field[0] = policy */
};
static const ProtobufCIntRange postman__send_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor postman__send_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.SendRequest",
  "SendRequest",
  "Postman__SendRequest",
  "Postman",
  sizeof(Postman__SendRequest),
  3,
  postman__send_request__field_descriptors,
  postman__send_request__field_indices_by_name,
  1,  postman__send_request__number_ranges,
  (ProtobufCMessageInit) postman__send_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor postman__message__field_descriptors[1] =
{
  {
    "send_request",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Postman__Message, send_request),
    &postman__send_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned postman__message__field_indices_by_name[] = {
  0,   /* field[0] = send_request */
};
static const ProtobufCIntRange postman__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor postman__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Postman.Message",
  "Message",
  "Postman__Message",
  "Postman",
  sizeof(Postman__Message),
  1,
  postman__message__field_descriptors,
  postman__message__field_indices_by_name,
  1,  postman__message__number_ranges,
  (ProtobufCMessageInit) postman__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue postman__priority__enum_values_by_number[2] =
{
  { "NORMAL", "POSTMAN__PRIORITY__NORMAL", 0 },
  { "URGENT", "POSTMAN__PRIORITY__URGENT", 9 },
};
static const ProtobufCIntRange postman__priority__value_ranges[] = {
{0, 0},{9, 1},{0, 2}
};
static const ProtobufCEnumValueIndex postman__priority__enum_values_by_name[2] =
{
  { "NORMAL", 0 },
  { "URGENT", 1 },
};
const ProtobufCEnumDescriptor postman__priority__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Postman.Priority",
  "Priority",
  "Postman__Priority",
  "Postman",
  2,
  postman__priority__enum_values_by_number,
  2,
  postman__priority__enum_values_by_name,
  2,
  postman__priority__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue postman__event__enum_values_by_number[28] =
{
  { "NONE_EVENT", "POSTMAN__EVENT__NONE_EVENT", 0 },
  { "CPU_HIGH", "POSTMAN__EVENT__CPU_HIGH", 1 },
  { "TRAFFIC_HIGH", "POSTMAN__EVENT__TRAFFIC_HIGH", 2 },
  { "HOST_DISCONN", "POSTMAN__EVENT__HOST_DISCONN", 3 },
  { "HOST_MAINTENANCE", "POSTMAN__EVENT__HOST_MAINTENANCE", 4 },
  { "HOST_MEM_HIGH", "POSTMAN__EVENT__HOST_MEM_HIGH", 5 },
  { "HOST_DISK_HIGH", "POSTMAN__EVENT__HOST_DISK_HIGH", 6 },
  { "HOST_CPU_HIGH", "POSTMAN__EVENT__HOST_CPU_HIGH", 7 },
  { "VM_STATE_CHG", "POSTMAN__EVENT__VM_STATE_CHG", 8 },
  { "RACK_EXPIRED", "POSTMAN__EVENT__RACK_EXPIRED", 9 },
  { "VM_EXPIRED", "POSTMAN__EVENT__VM_EXPIRED", 10 },
  { "DRBD_SPLIT_BRAIN", "POSTMAN__EVENT__DRBD_SPLIT_BRAIN", 11 },
  { "VM_RESTORE", "POSTMAN__EVENT__VM_RESTORE", 12 },
  { "USER_CHARGE", "POSTMAN__EVENT__USER_CHARGE", 13 },
  { "NSP_FAIL", "POSTMAN__EVENT__NSP_FAIL", 14 },
  { "USER_MAIL", "POSTMAN__EVENT__USER_MAIL", 15 },
  { "TALKER_CB_NSP_BOOTUP", "POSTMAN__EVENT__TALKER_CB_NSP_BOOTUP", 16 },
  { "TALKER_CONF_INTERFACE", "POSTMAN__EVENT__TALKER_CONF_INTERFACE", 17 },
  { "EVENT_FLIP_SIGN", "POSTMAN__EVENT__EVENT_FLIP_SIGN", 268435456 },
  { "CPU_HIGH_OVER", "POSTMAN__EVENT__CPU_HIGH_OVER", 268435457 },
  { "TRAFFIC_HIGH_OVER", "POSTMAN__EVENT__TRAFFIC_HIGH_OVER", 268435458 },
  { "HOST_DISCONN_OVER", "POSTMAN__EVENT__HOST_DISCONN_OVER", 268435459 },
  { "HOST_MAINTENANCE_OVER", "POSTMAN__EVENT__HOST_MAINTENANCE_OVER", 268435460 },
  { "HOST_MEM_HIGH_OVER", "POSTMAN__EVENT__HOST_MEM_HIGH_OVER", 268435461 },
  { "HOST_DISK_HIGH_OVER", "POSTMAN__EVENT__HOST_DISK_HIGH_OVER", 268435462 },
  { "HOST_CPU_HIGH_OVER", "POSTMAN__EVENT__HOST_CPU_HIGH_OVER", 268435463 },
  { "VM_STATE_CHG_OVER", "POSTMAN__EVENT__VM_STATE_CHG_OVER", 268435464 },
  { "NSP_FAIL_OVER", "POSTMAN__EVENT__NSP_FAIL_OVER", 268435470 },
};
static const ProtobufCIntRange postman__event__value_ranges[] = {
{0, 0},{268435456, 18},{268435470, 27},{0, 28}
};
static const ProtobufCEnumValueIndex postman__event__enum_values_by_name[28] =
{
  { "CPU_HIGH", 1 },
  { "CPU_HIGH_OVER", 19 },
  { "DRBD_SPLIT_BRAIN", 11 },
  { "EVENT_FLIP_SIGN", 18 },
  { "HOST_CPU_HIGH", 7 },
  { "HOST_CPU_HIGH_OVER", 25 },
  { "HOST_DISCONN", 3 },
  { "HOST_DISCONN_OVER", 21 },
  { "HOST_DISK_HIGH", 6 },
  { "HOST_DISK_HIGH_OVER", 24 },
  { "HOST_MAINTENANCE", 4 },
  { "HOST_MAINTENANCE_OVER", 22 },
  { "HOST_MEM_HIGH", 5 },
  { "HOST_MEM_HIGH_OVER", 23 },
  { "NONE_EVENT", 0 },
  { "NSP_FAIL", 14 },
  { "NSP_FAIL_OVER", 27 },
  { "RACK_EXPIRED", 9 },
  { "TALKER_CB_NSP_BOOTUP", 16 },
  { "TALKER_CONF_INTERFACE", 17 },
  { "TRAFFIC_HIGH", 2 },
  { "TRAFFIC_HIGH_OVER", 20 },
  { "USER_CHARGE", 13 },
  { "USER_MAIL", 15 },
  { "VM_EXPIRED", 10 },
  { "VM_RESTORE", 12 },
  { "VM_STATE_CHG", 8 },
  { "VM_STATE_CHG_OVER", 26 },
};
const ProtobufCEnumDescriptor postman__event__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Postman.Event",
  "Event",
  "Postman__Event",
  "Postman",
  28,
  postman__event__enum_values_by_number,
  28,
  postman__event__enum_values_by_name,
  3,
  postman__event__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue postman__resource__enum_values_by_number[11] =
{
  { "NONE_RESOURCE", "POSTMAN__RESOURCE__NONE_RESOURCE", 0 },
  { "HOST", "POSTMAN__RESOURCE__HOST", 1 },
  { "VGW", "POSTMAN__RESOURCE__VGW", 2 },
  { "VM", "POSTMAN__RESOURCE__VM", 3 },
  { "RACK", "POSTMAN__RESOURCE__RACK", 4 },
  { "VMWAF", "POSTMAN__RESOURCE__VMWAF", 5 },
  { "CHARGE", "POSTMAN__RESOURCE__CHARGE", 6 },
  { "USER", "POSTMAN__RESOURCE__USER", 7 },
  { "VGATEWAY", "POSTMAN__RESOURCE__VGATEWAY", 8 },
  { "VINTERFACE", "POSTMAN__RESOURCE__VINTERFACE", 9 },
  { "VALVE", "POSTMAN__RESOURCE__VALVE", 10 },
};
static const ProtobufCIntRange postman__resource__value_ranges[] = {
{0, 0},{0, 11}
};
static const ProtobufCEnumValueIndex postman__resource__enum_values_by_name[11] =
{
  { "CHARGE", 6 },
  { "HOST", 1 },
  { "NONE_RESOURCE", 0 },
  { "RACK", 4 },
  { "USER", 7 },
  { "VALVE", 10 },
  { "VGATEWAY", 8 },
  { "VGW", 2 },
  { "VINTERFACE", 9 },
  { "VM", 3 },
  { "VMWAF", 5 },
};
const ProtobufCEnumDescriptor postman__resource__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Postman.Resource",
  "Resource",
  "Postman__Resource",
  "Postman",
  11,
  postman__resource__enum_values_by_number,
  11,
  postman__resource__enum_values_by_name,
  1,
  postman__resource__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue postman__aggregate_id__enum_values_by_number[9] =
{
  { "AGG_NO_AGGREGATE", "POSTMAN__AGGREGATE_ID__AGG_NO_AGGREGATE", 0 },
  { "AGG_ALARM_EVENT", "POSTMAN__AGGREGATE_ID__AGG_ALARM_EVENT", 1 },
  { "AGG_ALARM_OVER_EVENT", "POSTMAN__AGGREGATE_ID__AGG_ALARM_OVER_EVENT", 2 },
  { "AGG_HOST_USAGE_ALARM_EVENT", "POSTMAN__AGGREGATE_ID__AGG_HOST_USAGE_ALARM_EVENT", 3 },
  { "AGG_VM_USAGE_ALARM_EVENT", "POSTMAN__AGGREGATE_ID__AGG_VM_USAGE_ALARM_EVENT", 4 },
  { "AGG_VM_RESTORE", "POSTMAN__AGGREGATE_ID__AGG_VM_RESTORE", 5 },
  { "AGG_TALKER_CB_NSP_BOOTUP", "POSTMAN__AGGREGATE_ID__AGG_TALKER_CB_NSP_BOOTUP", 6 },
  { "AGG_TALKER_CONF_INTERFACE", "POSTMAN__AGGREGATE_ID__AGG_TALKER_CONF_INTERFACE", 7 },
  { "AGG_BUNDLE_SEND_REQUEST", "POSTMAN__AGGREGATE_ID__AGG_BUNDLE_SEND_REQUEST", 8 },
};
static const ProtobufCIntRange postman__aggregate_id__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex postman__aggregate_id__enum_values_by_name[9] =
{
  { "AGG_ALARM_EVENT", 1 },
  { "AGG_ALARM_OVER_EVENT", 2 },
  { "AGG_BUNDLE_SEND_REQUEST", 8 },
  { "AGG_HOST_USAGE_ALARM_EVENT", 3 },
  { "AGG_NO_AGGREGATE", 0 },
  { "AGG_TALKER_CB_NSP_BOOTUP", 6 },
  { "AGG_TALKER_CONF_INTERFACE", 7 },
  { "AGG_VM_RESTORE", 5 },
  { "AGG_VM_USAGE_ALARM_EVENT", 4 },
};
const ProtobufCEnumDescriptor postman__aggregate_id__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Postman.AggregateId",
  "AggregateId",
  "Postman__AggregateId",
  "Postman",
  9,
  postman__aggregate_id__enum_values_by_number,
  9,
  postman__aggregate_id__enum_values_by_name,
  1,
  postman__aggregate_id__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue postman__mail_type__enum_values_by_number[13] =
{
  { "NONE_MAIL_TYPE", "POSTMAN__MAIL_TYPE__NONE_MAIL_TYPE", 0 },
  { "ALARM_MAIL", "POSTMAN__MAIL_TYPE__ALARM_MAIL", 1 },
  { "ALARM_OVER_MAIL", "POSTMAN__MAIL_TYPE__ALARM_OVER_MAIL", 2 },
  { "NOTIFY_MAIL", "POSTMAN__MAIL_TYPE__NOTIFY_MAIL", 3 },
  { "NOTIFY_OVER_MAIL", "POSTMAN__MAIL_TYPE__NOTIFY_OVER_MAIL", 4 },
  { "LICENSE_EXPIRE_MAIL", "POSTMAN__MAIL_TYPE__LICENSE_EXPIRE_MAIL", 5 },
  { "SERVICE_EXPIRE_MAIL", "POSTMAN__MAIL_TYPE__SERVICE_EXPIRE_MAIL", 6 },
  { "USER_USAGE_FORM_MAIL", "POSTMAN__MAIL_TYPE__USER_USAGE_FORM_MAIL", 7 },
  { "USER_CHARGE_FORM_MAIL", "POSTMAN__MAIL_TYPE__USER_CHARGE_FORM_MAIL", 8 },
  { "RAW_STRING", "POSTMAN__MAIL_TYPE__RAW_STRING", 9 },
  { "BALANCE_LACKED_MAIL", "POSTMAN__MAIL_TYPE__BALANCE_LACKED_MAIL", 10 },
  { "BALANCE_SOON_LACK_MAIL", "POSTMAN__MAIL_TYPE__BALANCE_SOON_LACK_MAIL", 11 },
  { "BALANCE_LACKED_SUMMARY_MAIL", "POSTMAN__MAIL_TYPE__BALANCE_LACKED_SUMMARY_MAIL", 12 },
};
static const ProtobufCIntRange postman__mail_type__value_ranges[] = {
{0, 0},{0, 13}
};
static const ProtobufCEnumValueIndex postman__mail_type__enum_values_by_name[13] =
{
  { "ALARM_MAIL", 1 },
  { "ALARM_OVER_MAIL", 2 },
  { "BALANCE_LACKED_MAIL", 10 },
  { "BALANCE_LACKED_SUMMARY_MAIL", 12 },
  { "BALANCE_SOON_LACK_MAIL", 11 },
  { "LICENSE_EXPIRE_MAIL", 5 },
  { "NONE_MAIL_TYPE", 0 },
  { "NOTIFY_MAIL", 3 },
  { "NOTIFY_OVER_MAIL", 4 },
  { "RAW_STRING", 9 },
  { "SERVICE_EXPIRE_MAIL", 6 },
  { "USER_CHARGE_FORM_MAIL", 8 },
  { "USER_USAGE_FORM_MAIL", 7 },
};
const ProtobufCEnumDescriptor postman__mail_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Postman.MailType",
  "MailType",
  "Postman__MailType",
  "Postman",
  13,
  postman__mail_type__enum_values_by_number,
  13,
  postman__mail_type__enum_values_by_name,
  1,
  postman__mail_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
